begin;

do $$
declare
  required_relation text;
begin
  foreach required_relation in array array[
    'public.product_categories',
    'public.attribute_types',
    'public.attribute_values',
    'public.category_attributes',
    'public.products',
    'public.product_attribute_values',
    'public.product_variants',
    'public.variant_attribute_values',
    'public.stock_movements',
    'public.audit_events'
  ]
  loop
    if to_regclass(required_relation) is null then
      raise exception using
        errcode = '42P01',
        message = format(
          'Required relation %s is missing. Run main_schema.sql for a new project.',
          required_relation
        );
    end if;
  end loop;
end;
$$;

alter table public.category_attributes
  add column if not exists required_from timestamptz;

alter table public.products
  add column if not exists brand text,
  add column if not exists product_number bigint
    generated by default as identity;

alter table public.product_variants
  add column if not exists barcode text;

create unique index if not exists product_variants_barcode_unique
  on public.product_variants (barcode)
  where barcode is not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.products'::regclass
      and conname = 'products_product_number_unique'
  ) then
    alter table public.products
      add constraint products_product_number_unique
      unique (product_number);
  end if;
end;
$$;

create table if not exists public.product_options (
  product_id uuid not null
    references public.products (id) on delete cascade,
  attribute_type_id uuid not null
    references public.attribute_types (id) on delete restrict,
  is_required boolean not null default true,
  is_variant_axis boolean not null default true,
  sort_order integer not null default 0,
  required_from timestamptz,
  created_by uuid not null references auth.users (id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, attribute_type_id),
  constraint product_options_sort_order_nonnegative
    check (sort_order >= 0)
);

drop trigger if exists product_options_set_updated_at
  on public.product_options;
create trigger product_options_set_updated_at
before update on public.product_options
for each row execute function private.set_updated_at();

insert into public.product_options (
  product_id,
  attribute_type_id,
  is_required,
  is_variant_axis,
  sort_order,
  required_from,
  created_by
)
select
  referenced.product_id,
  referenced.attribute_type_id,
  coalesce(configuration.is_required, true),
  referenced.is_variant_axis,
  coalesce(configuration.sort_order, referenced.sort_order),
  case
    when coalesce(configuration.is_required, true)
      then referenced.created_at
    else null
  end,
  referenced.created_by
from (
  select
    products.id as product_id,
    product_attribute_values.attribute_type_id,
    false as is_variant_axis,
    row_number() over (
      partition by products.id
      order by product_attribute_values.attribute_type_id
    )::integer - 1 as sort_order,
    products.created_at,
    products.created_by
  from public.products
  join public.product_attribute_values
    on product_attribute_values.product_id = products.id
  union
  select
    products.id,
    variant_attribute_values.attribute_type_id,
    true,
    row_number() over (
      partition by products.id
      order by variant_attribute_values.attribute_type_id
    )::integer - 1,
    products.created_at,
    products.created_by
  from public.products
  join public.product_variants
    on product_variants.product_id = products.id
  join public.variant_attribute_values
    on variant_attribute_values.variant_id = product_variants.id
) as referenced
left join lateral (
  select
    category_attributes.is_required,
    category_attributes.sort_order
  from public.category_attributes
  where category_attributes.attribute_type_id =
      referenced.attribute_type_id
    and category_attributes.category_id in (
      (
        select category_id
        from public.products
        where id = referenced.product_id
      ),
      (
        select product_categories.parent_id
        from public.products
        join public.product_categories
          on product_categories.id = products.category_id
        where products.id = referenced.product_id
      )
    )
  order by (
    category_attributes.category_id = (
      select category_id
      from public.products
      where id = referenced.product_id
    )
  ) desc
  limit 1
) as configuration on true
on conflict (product_id, attribute_type_id) do nothing;

alter table public.product_options enable row level security;
alter table public.product_options force row level security;

drop policy if exists product_options_select on public.product_options;
create policy product_options_select
on public.product_options
for select
to authenticated
using (true);

drop policy if exists product_options_manage on public.product_options;
create policy product_options_manage
on public.product_options
for all
to authenticated
using ((select private.is_store_operator()))
with check ((select private.is_store_operator()));

revoke all on public.product_options from public, anon, authenticated;
grant select, insert, update, delete
  on public.product_options to authenticated;

create or replace function public.create_product_with_variants(
  target_category_id uuid,
  product_name text,
  product_brand text,
  product_description text,
  selected_product_values jsonb,
  selected_product_options jsonb,
  target_variants jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  new_product_id uuid;
  new_variant_id uuid;
  option_payload jsonb;
  variant_payload jsonb;
  variant_attributes jsonb;
  selected_value record;
  response_variants jsonb := '[]'::jsonb;
  variant_count integer;
  distinct_client_key_count integer;
  price_value bigint;
  opening_stock_value integer;
  threshold_value integer;
  normalized_sku text;
  normalized_barcode text;
  client_key text;
  attribute_signature text;
begin
  if actor is null or not private.is_store_operator() then
    raise exception using errcode = '42501',
      message = 'Store-manager access is required.';
  end if;

  if nullif(btrim(product_name), '') is null then
    raise exception using errcode = '22023',
      message = 'Product name is required.';
  end if;

  if jsonb_typeof(coalesce(selected_product_values, '{}'::jsonb))
      <> 'object'
    or jsonb_typeof(coalesce(selected_product_options, '[]'::jsonb))
      <> 'array'
    or jsonb_typeof(target_variants) is distinct from 'array' then
    raise exception using errcode = '22023',
      message = 'Product options and stock items are invalid.';
  end if;

  if jsonb_array_length(target_variants) = 0 then
    raise exception using errcode = '22023',
      message = 'Add at least one stock item.';
  end if;

  if not exists (
    select 1 from public.product_categories
    where id = target_category_id and is_active
  ) then
    raise exception using errcode = '23503',
      message = 'Choose an active category.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(selected_product_options) as option(value)
    where jsonb_typeof(option.value) <> 'object'
      or nullif(option.value ->> 'attribute_type_id', '') is null
      or jsonb_typeof(option.value -> 'is_required') <> 'boolean'
      or jsonb_typeof(option.value -> 'is_variant_axis') <> 'boolean'
      or jsonb_typeof(option.value -> 'sort_order') <> 'number'
      or (option.value ->> 'sort_order')::integer < 0
  ) then
    raise exception using errcode = '22023',
      message = 'Every selected product option is invalid.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(selected_product_options) as option(value)
    group by option.value ->> 'attribute_type_id'
    having count(*) > 1
  ) then
    raise exception using errcode = '23505',
      message = 'Each product option can be selected only once.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(selected_product_options) as option(value)
    where not exists (
      select 1
      from public.attribute_values
      where attribute_type_id =
        (option.value ->> 'attribute_type_id')::uuid
    )
  ) then
    raise exception using errcode = '23514',
      message = 'Every selected product option needs an allowed value.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(selected_product_options) as option(value)
    where (option.value ->> 'is_required')::boolean
      and not (option.value ->> 'is_variant_axis')::boolean
      and not (
        coalesce(selected_product_values, '{}'::jsonb)
        ? (option.value ->> 'attribute_type_id')
      )
  ) then
    raise exception using errcode = '23514',
      message = 'Choose every required product specification.';
  end if;

  for selected_value in
    select key::uuid as attribute_type_id,
      value::uuid as attribute_value_id
    from jsonb_each_text(
      coalesce(selected_product_values, '{}'::jsonb)
    )
  loop
    if not exists (
      select 1
      from jsonb_array_elements(selected_product_options) as option(value)
      join public.attribute_values
        on attribute_values.attribute_type_id =
          (option.value ->> 'attribute_type_id')::uuid
       and attribute_values.id = selected_value.attribute_value_id
      where (option.value ->> 'attribute_type_id')::uuid =
          selected_value.attribute_type_id
        and not (option.value ->> 'is_variant_axis')::boolean
    ) then
      raise exception using errcode = '23514',
        message = 'A product value belongs to an unselected option.';
    end if;
  end loop;

  select count(*), count(distinct value ->> 'client_key')
  into variant_count, distinct_client_key_count
  from jsonb_array_elements(target_variants);

  if variant_count <> distinct_client_key_count
    or exists (
      select 1 from jsonb_array_elements(target_variants)
      where jsonb_typeof(value) <> 'object'
        or nullif(btrim(value ->> 'client_key'), '') is null
    ) then
    raise exception using errcode = '23514',
      message = 'Every stock item needs a unique client key.';
  end if;

  for variant_payload in
    select value from jsonb_array_elements(target_variants)
  loop
    variant_attributes := coalesce(
      variant_payload -> 'attributes', '{}'::jsonb
    );
    if jsonb_typeof(variant_attributes) <> 'object' then
      raise exception using errcode = '22023',
        message = 'Stock item options must be an object.';
    end if;

    if exists (
      select 1
      from jsonb_array_elements(selected_product_options) as option(value)
      where (option.value ->> 'is_required')::boolean
        and (option.value ->> 'is_variant_axis')::boolean
        and not (
          variant_attributes
          ? (option.value ->> 'attribute_type_id')
        )
    ) then
      raise exception using errcode = '23514',
        message = 'Choose every required stock-item option.';
    end if;

    for selected_value in
      select key::uuid as attribute_type_id,
        value::uuid as attribute_value_id
      from jsonb_each_text(variant_attributes)
    loop
      if not exists (
        select 1
        from jsonb_array_elements(selected_product_options)
          as option(value)
        join public.attribute_values
          on attribute_values.attribute_type_id =
            (option.value ->> 'attribute_type_id')::uuid
         and attribute_values.id =
            selected_value.attribute_value_id
        where (option.value ->> 'attribute_type_id')::uuid =
            selected_value.attribute_type_id
          and (option.value ->> 'is_variant_axis')::boolean
      ) then
        raise exception using errcode = '23514',
          message = 'A stock-item value belongs to an unselected option.';
      end if;
    end loop;
  end loop;

  insert into public.products (
    category_id, name, brand, description, created_by
  ) values (
    target_category_id, btrim(product_name),
    nullif(btrim(product_brand), ''),
    nullif(btrim(product_description), ''), actor
  )
  returning id into new_product_id;

  for option_payload in
    select value
    from jsonb_array_elements(selected_product_options)
  loop
    insert into public.product_options (
      product_id, attribute_type_id, is_required,
      is_variant_axis, sort_order, required_from, created_by
    ) values (
      new_product_id,
      (option_payload ->> 'attribute_type_id')::uuid,
      (option_payload ->> 'is_required')::boolean,
      (option_payload ->> 'is_variant_axis')::boolean,
      (option_payload ->> 'sort_order')::integer,
      case when (option_payload ->> 'is_required')::boolean
        then now() else null end,
      actor
    );
  end loop;

  for selected_value in
    select key::uuid as attribute_type_id,
      value::uuid as attribute_value_id
    from jsonb_each_text(
      coalesce(selected_product_values, '{}'::jsonb)
    )
  loop
    insert into public.product_attribute_values (
      product_id, attribute_type_id, attribute_value_id
    ) values (
      new_product_id, selected_value.attribute_type_id,
      selected_value.attribute_value_id
    );
  end loop;

  for variant_payload in
    select value from jsonb_array_elements(target_variants)
  loop
    client_key := nullif(btrim(variant_payload ->> 'client_key'), '');
    normalized_sku := upper(btrim(variant_payload ->> 'sku'));
    normalized_barcode :=
      nullif(btrim(variant_payload ->> 'barcode'), '');
    price_value := (variant_payload ->> 'price_paise')::bigint;
    opening_stock_value :=
      (variant_payload ->> 'opening_stock')::integer;
    threshold_value :=
      (variant_payload ->> 'low_stock_threshold')::integer;
    variant_attributes := coalesce(
      variant_payload -> 'attributes', '{}'::jsonb
    );

    if nullif(normalized_sku, '') is null
      or price_value is null
      or opening_stock_value is null
      or threshold_value is null then
      raise exception using errcode = '22023',
        message = 'Every stock item needs SKU, price, stock, and threshold.';
    end if;
    if price_value < 0
      or opening_stock_value < 0
      or threshold_value < 0 then
      raise exception using errcode = '23514',
        message = 'Price, stock, and threshold cannot be negative.';
    end if;

    select coalesce(
      string_agg(key || '=' || value, ',' order by key),
      'default'
    )
    into attribute_signature
    from jsonb_each_text(variant_attributes);

    insert into public.product_variants (
      product_id, sku, barcode, attribute_signature, price_paise,
      current_stock, low_stock_threshold, created_by
    ) values (
      new_product_id, normalized_sku, normalized_barcode,
      attribute_signature, price_value, opening_stock_value,
      threshold_value, actor
    )
    returning id into new_variant_id;

    for selected_value in
      select key::uuid as attribute_type_id,
        value::uuid as attribute_value_id
      from jsonb_each_text(variant_attributes)
    loop
      insert into public.variant_attribute_values (
        variant_id, attribute_type_id, attribute_value_id
      ) values (
        new_variant_id, selected_value.attribute_type_id,
        selected_value.attribute_value_id
      );
    end loop;

    if opening_stock_value > 0 then
      insert into public.stock_movements (
        variant_id, movement_type, quantity_before, quantity_delta,
        quantity_after, reason, actor_id
      ) values (
        new_variant_id, 'initial', 0, opening_stock_value,
        opening_stock_value, 'Opening stock', actor
      );
    end if;

    response_variants := response_variants || jsonb_build_array(
      jsonb_build_object(
        'client_key', client_key,
        'variant_id', new_variant_id
      )
    );
  end loop;

  insert into public.audit_events (
    actor_id, action, entity_type, entity_id, metadata
  ) values (
    actor, 'product.created', 'product', new_product_id,
    jsonb_build_object(
      'variant_count', variant_count,
      'product_option_count',
        jsonb_array_length(selected_product_options)
    )
  );

  return jsonb_build_object(
    'product_id', new_product_id,
    'variants', response_variants
  );
end;
$$;

create or replace function public.create_product_with_variants(
  target_category_id uuid,
  product_name text,
  product_brand text,
  product_description text,
  selected_product_values jsonb,
  target_variants jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  inferred_options jsonb;
begin
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'attribute_type_id', submitted.attribute_type_id,
        'is_required', true,
        'is_variant_axis', submitted.is_variant_axis,
        'sort_order', submitted.sort_order
      )
      order by submitted.sort_order
    ),
    '[]'::jsonb
  )
  into inferred_options
  from (
    select
      key::uuid as attribute_type_id,
      false as is_variant_axis,
      row_number() over (order by key)::integer - 1 as sort_order
    from jsonb_each_text(
      coalesce(selected_product_values, '{}'::jsonb)
    )
    union
    select
      submitted_variant_keys.attribute_type_id,
      true,
      row_number() over (
        order by submitted_variant_keys.attribute_type_id
      )::integer - 1
    from (
      select distinct variant_key.key::uuid as attribute_type_id
      from jsonb_array_elements(target_variants) as variants(value)
      cross join lateral jsonb_each_text(
        coalesce(variants.value -> 'attributes', '{}'::jsonb)
      ) as variant_key
    ) as submitted_variant_keys
  ) as submitted;

  return public.create_product_with_variants(
    target_category_id,
    product_name,
    product_brand,
    product_description,
    selected_product_values,
    inferred_options,
    target_variants
  );
end;
$$;

revoke all on function public.create_product_with_variants(
  uuid, text, text, text, jsonb, jsonb, jsonb
) from public, anon;
revoke all on function public.create_product_with_variants(
  uuid, text, text, text, jsonb, jsonb
) from public, anon;

grant execute on function public.create_product_with_variants(
  uuid, text, text, text, jsonb, jsonb, jsonb
) to authenticated, service_role;
grant execute on function public.create_product_with_variants(
  uuid, text, text, text, jsonb, jsonb
) to authenticated, service_role;

notify pgrst, 'reload schema';

commit;
